"""Observability instrumentation, metrics, and audit event definitions for Enterprise LLM Gateway."""

from app.observability.metrics import MetricsRegistry, get_metrics_registry

# Audit Event Identifiers (Section 42)
AUDIT_LLM_POLICY_DENIED = "LLM_POLICY_DENIED"
AUDIT_LLM_REQUEST_EXECUTED = "LLM_REQUEST_EXECUTED"
AUDIT_LLM_REQUEST_FAILED = "LLM_REQUEST_FAILED"
AUDIT_LLM_FALLBACK_USED = "LLM_FALLBACK_USED"
AUDIT_LLM_BUDGET_EXCEEDED = "LLM_BUDGET_EXCEEDED"
AUDIT_LLM_MODEL_CHANGED = "LLM_MODEL_CHANGED"
AUDIT_LLM_PROVIDER_DISABLED = "LLM_PROVIDER_DISABLED"


class LLMInstrumentation:
    """Provides strictly low-cardinality Prometheus metrics and operational telemetry for LLM Gateway."""

    def __init__(self, registry: MetricsRegistry | None = None) -> None:
        self.registry = registry or get_metrics_registry()

    @staticmethod
    def extract_model_family(model_name: str) -> str:
        """Extract low-cardinality model family label (e.g. gpt-4o, gpt-3.5, claude-3, mock)."""
        lower = model_name.lower()
        if "gpt-4" in lower:
            return "gpt-4"
        if "gpt-3" in lower:
            return "gpt-3.5"
        if "o1" in lower or "o3" in lower:
            return "o-series"
        if "claude" in lower:
            return "claude"
        if "llama" in lower:
            return "llama"
        if "mistral" in lower:
            return "mistral"
        if "mock" in lower or "deterministic" in lower:
            return "deterministic"
        return "other"

    def record_request(
        self,
        *,
        provider: str,
        model: str,
        task_type: str,
        status: str,
        duration_s: float,
        input_tokens: int = 0,
        output_tokens: int = 0,
        estimated_cost: float = 0.0,
        fallback_used: bool = False,
        cache_hit: bool = False,
    ) -> None:
        model_family = self.extract_model_family(model)
        labels = {
            "provider": provider.lower(),
            "model_family": model_family,
            "task_type": task_type.lower(),
            "status": status.lower(),
            "fallback": "true" if fallback_used else "false",
            "cache_status": "hit" if cache_hit else "miss",
        }

        # Request counter
        self.registry.increment(
            "llm_requests_total",
            value=1.0,
            labels=labels,
            description="Total count of requests processed by LLM Gateway",
        )

        if status.lower() not in ("success", "ok"):
            self.registry.increment(
                "llm_requests_failed_total",
                value=1.0,
                labels={
                    "provider": provider.lower(),
                    "model_family": model_family,
                    "task_type": task_type.lower(),
                    "status": status.lower(),
                },
                description="Total count of failed LLM Gateway requests",
            )

        # Duration histogram / gauge
        self.registry.observe(
            "llm_request_duration_seconds",
            value=duration_s,
            labels={
                "provider": provider.lower(),
                "model_family": model_family,
                "task_type": task_type.lower(),
            },
            description="Latency of LLM Gateway requests in seconds",
        )

        # Token counters
        if input_tokens > 0:
            self.registry.increment(
                "llm_input_tokens_total",
                value=float(input_tokens),
                labels={
                    "provider": provider.lower(),
                    "model_family": model_family,
                    "task_type": task_type.lower(),
                },
                description="Total input tokens consumed by LLM invocations",
            )
        if output_tokens > 0:
            self.registry.increment(
                "llm_output_tokens_total",
                value=float(output_tokens),
                labels={
                    "provider": provider.lower(),
                    "model_family": model_family,
                    "task_type": task_type.lower(),
                },
                description="Total output tokens generated by LLM invocations",
            )

        # Estimated cost counter
        if estimated_cost > 0.0:
            self.registry.increment(
                "llm_estimated_cost_total",
                value=estimated_cost,
                labels={
                    "provider": provider.lower(),
                    "model_family": model_family,
                    "task_type": task_type.lower(),
                },
                description="Total estimated USD cost for LLM invocations",
            )

        # Fallback counter
        if fallback_used:
            self.registry.increment(
                "llm_fallback_total",
                value=1.0,
                labels={
                    "provider": provider.lower(),
                    "model_family": model_family,
                    "task_type": task_type.lower(),
                },
                description="Total count of requests where fallback was engaged",
            )

        # Cache hit counter
        if cache_hit:
            self.registry.increment(
                "llm_cache_hit_total",
                value=1.0,
                labels={
                    "provider": provider.lower(),
                    "model_family": model_family,
                    "task_type": task_type.lower(),
                },
                description="Total count of cached responses returned by LLM Gateway",
            )

    def record_circuit_open(self, provider: str) -> None:
        self.registry.increment(
            "llm_provider_circuit_open_total",
            value=1.0,
            labels={"provider": provider.lower()},
            description="Count of circuit breaker trips opening for an LLM provider",
        )

    def record_budget_rejection(self, task_type: str, reason: str) -> None:
        self.registry.increment(
            "llm_budget_rejected_total",
            value=1.0,
            labels={"task_type": task_type.lower(), "status": reason.lower()},
            description="Count of requests rejected due to token or cost budget limits",
        )
