"""Unit tests verifying RBAC permission catalog, role definitions, and schema contracts."""

from app.rbac.catalog import (
    DEFAULT_ROLE_PERMISSIONS,
    PERM_AGENTS_APPROVE,
    PERM_AGENTS_CANCEL,
    PERM_AGENTS_CREATE,
    PERM_AGENTS_EXECUTE,
    PERM_AGENTS_READ,
    PERM_AGENTS_RESUME,
    PERM_AI_ANALYZE,
    PERM_AI_CHAT,
    PERM_ANALYTICS_EXECUTE,
    PERM_ANALYTICS_READ,
    PERM_AUDIT_READ,
    PERM_COMPLIANCE_ACCESS_REVIEW,
    PERM_COMPLIANCE_ASSESS,
    PERM_COMPLIANCE_EVIDENCE_MANAGE,
    PERM_COMPLIANCE_EVIDENCE_READ,
    PERM_COMPLIANCE_FINDINGS_MANAGE,
    PERM_COMPLIANCE_FINDINGS_READ,
    PERM_COMPLIANCE_MANAGE,
    PERM_COMPLIANCE_PRIVACY_MANAGE,
    PERM_COMPLIANCE_READ,
    PERM_COMPLIANCE_RETENTION_MANAGE,
    PERM_COMPLIANCE_RISK_ACCEPTANCE,
    PERM_COMPLIANCE_SECURITY_ADMIN,
    PERM_DATA_SOURCES_DELETE,
    PERM_DATA_SOURCES_READ,
    PERM_DATA_SOURCES_WRITE,
    PERM_DATASET_CREATE,
    PERM_DATASET_DELETE,
    PERM_DATASET_INGEST,
    PERM_DATASET_PROFILE,
    PERM_DATASET_READ,
    PERM_DATASET_UPDATE,
    PERM_DATASET_VERSIONS,
    PERM_DATASETS_DELETE,
    PERM_DATASETS_READ,
    PERM_DATASETS_WRITE,
    PERM_DATASOURCE_CREATE,
    PERM_DATASOURCE_DELETE,
    PERM_DATASOURCE_QUERY,
    PERM_DATASOURCE_READ,
    PERM_DATASOURCE_SCHEMA,
    PERM_DATASOURCE_SYNC,
    PERM_DATASOURCE_TEST,
    PERM_DATASOURCE_UPDATE,
    PERM_DOCUMENTS_DELETE,
    PERM_DOCUMENTS_MANAGE,
    PERM_DOCUMENTS_READ,
    PERM_DOCUMENTS_WRITE,
    PERM_EVALUATION_BENCHMARK_MANAGE,
    PERM_EVALUATION_COMPARE,
    PERM_EVALUATION_CREATE,
    PERM_EVALUATION_HUMAN_REVIEW,
    PERM_EVALUATION_MONITOR_READ,
    PERM_EVALUATION_QUALITY_GATE_READ,
    PERM_EVALUATION_READ,
    PERM_EVALUATION_RELEASE_APPROVE,
    PERM_EVALUATION_RUN,
    PERM_EVALUATION_RUN_EXECUTE,
    PERM_FINOPS_ANOMALY_READ,
    PERM_FINOPS_BUDGET_MANAGE,
    PERM_FINOPS_BUDGET_READ,
    PERM_FINOPS_MANAGE,
    PERM_FINOPS_OPTIMIZATION_READ,
    PERM_FINOPS_POLICY_MANAGE,
    PERM_FINOPS_PRICING_MANAGE,
    PERM_FINOPS_QUOTA_MANAGE,
    PERM_FINOPS_READ,
    PERM_FINOPS_RECONCILIATION_READ,
    PERM_GOVERNANCE_APPROVE,
    PERM_GOVERNANCE_CREATE,
    PERM_GOVERNANCE_MANAGE_POLICY,
    PERM_GOVERNANCE_READ,
    PERM_GOVERNANCE_REJECT,
    PERM_GOVERNANCE_REVIEW,
    PERM_GOVERNANCE_VIEW_AUDIT,
    PERM_GRAPH_CREATE,
    PERM_GRAPH_DELETE,
    PERM_GRAPH_PUBLISH,
    PERM_GRAPH_READ,
    PERM_GRAPH_TRAVERSE,
    PERM_GRAPH_UPDATE,
    PERM_JOBS_ADMIN,
    PERM_JOBS_CANCEL,
    PERM_JOBS_CREATE,
    PERM_JOBS_READ,
    PERM_JOBS_RETRY,
    PERM_LLM_MANAGE,
    PERM_LLM_MODEL_APPROVE,
    PERM_LLM_MODEL_DISABLE,
    PERM_LLM_POLICY_READ,
    PERM_LLM_POLICY_UPDATE,
    PERM_LLM_READ,
    PERM_LLM_USAGE_READ,
    PERM_MEMORY_ADMIN,
    PERM_MEMORY_CREATE,
    PERM_MEMORY_DELETE,
    PERM_MEMORY_READ,
    PERM_MEMORY_UPDATE,
    PERM_OBSERVABILITY_HEALTH,
    PERM_OBSERVABILITY_METRICS,
    PERM_OBSERVABILITY_READ,
    PERM_ORCHESTRATION_EXECUTE,
    PERM_ORCHESTRATION_MANAGE,
    PERM_ORCHESTRATION_READ,
    PERM_ORGANIZATION_MANAGE,
    PERM_ORGANIZATION_READ,
    PERM_RELIABILITY_MANAGE,
    PERM_RELIABILITY_READ,
    PERM_RELIABILITY_READINESS,
    PERM_RELIABILITY_RUN,
    PERM_REPORTS_ARCHIVE,
    PERM_REPORTS_CREATE,
    PERM_REPORTS_DELETE,
    PERM_REPORTS_EXPORT,
    PERM_REPORTS_PUBLISH,
    PERM_REPORTS_READ,
    PERM_REPORTS_UPDATE,
    PERM_SEMANTIC_CREATE,
    PERM_SEMANTIC_DELETE,
    PERM_SEMANTIC_PUBLISH,
    PERM_SEMANTIC_READ,
    PERM_SEMANTIC_UPDATE,
    PERM_SEMANTIC_VERIFY,
    PERM_SRE_ALERT_MANAGE,
    PERM_SRE_ALERT_READ,
    PERM_SRE_INCIDENT_MANAGE,
    PERM_SRE_INCIDENT_READ,
    PERM_SRE_MAINTENANCE_MANAGE,
    PERM_SRE_RELEASE_GATE_READ,
    PERM_SRE_RUNBOOK_MANAGE,
    PERM_SRE_RUNBOOK_READ,
    PERM_SRE_SLO_MANAGE,
    PERM_SRE_SLO_READ,
    PERM_USAGE_READ,
    PERM_USERS_INVITE,
    PERM_USERS_MANAGE,
    PERM_USERS_READ,
    PERM_USERS_REMOVE,
    ROLE_ADMIN,
    ROLE_ANALYST,
    ROLE_VIEWER,
    SYSTEM_PERMISSIONS,
    SYSTEM_ROLES,
)


def test_permission_catalog_completeness() -> None:
    """Verify all permissions are registered with descriptive metadata."""
    expected_permissions = {
        PERM_USERS_READ,
        PERM_USERS_MANAGE,
        PERM_USERS_INVITE,
        PERM_USERS_REMOVE,
        PERM_ORGANIZATION_READ,
        PERM_ORGANIZATION_MANAGE,
        PERM_DOCUMENTS_READ,
        PERM_DOCUMENTS_WRITE,
        PERM_DOCUMENTS_DELETE,
        PERM_DOCUMENTS_MANAGE,
        PERM_DATASETS_READ,
        PERM_DATASETS_WRITE,
        PERM_DATASETS_DELETE,
        PERM_DATA_SOURCES_READ,
        PERM_DATA_SOURCES_WRITE,
        PERM_DATA_SOURCES_DELETE,
        PERM_REPORTS_READ,
        PERM_REPORTS_CREATE,
        PERM_REPORTS_UPDATE,
        PERM_REPORTS_DELETE,
        PERM_REPORTS_PUBLISH,
        PERM_REPORTS_EXPORT,
        PERM_REPORTS_ARCHIVE,
        PERM_ANALYTICS_READ,
        PERM_ANALYTICS_EXECUTE,
        PERM_AI_CHAT,
        PERM_AI_ANALYZE,
        PERM_AUDIT_READ,
        PERM_USAGE_READ,
        PERM_EVALUATION_READ,
        PERM_EVALUATION_CREATE,
        PERM_EVALUATION_RUN,
        PERM_EVALUATION_COMPARE,
        PERM_OBSERVABILITY_READ,
        PERM_OBSERVABILITY_METRICS,
        PERM_OBSERVABILITY_HEALTH,
        PERM_JOBS_READ,
        PERM_JOBS_CREATE,
        PERM_JOBS_CANCEL,
        PERM_JOBS_RETRY,
        PERM_JOBS_ADMIN,
        PERM_AGENTS_READ,
        PERM_AGENTS_CREATE,
        PERM_AGENTS_EXECUTE,
        PERM_AGENTS_CANCEL,
        PERM_AGENTS_APPROVE,
        PERM_AGENTS_RESUME,
        PERM_MEMORY_READ,
        PERM_MEMORY_CREATE,
        PERM_MEMORY_UPDATE,
        PERM_MEMORY_DELETE,
        PERM_MEMORY_ADMIN,
        PERM_DATASOURCE_READ,
        PERM_DATASOURCE_CREATE,
        PERM_DATASOURCE_UPDATE,
        PERM_DATASOURCE_DELETE,
        PERM_DATASOURCE_TEST,
        PERM_DATASOURCE_QUERY,
        PERM_DATASOURCE_SYNC,
        PERM_DATASOURCE_SCHEMA,
        PERM_DATASET_CREATE,
        PERM_DATASET_DELETE,
        PERM_DATASET_INGEST,
        PERM_DATASET_PROFILE,
        PERM_DATASET_READ,
        PERM_DATASET_UPDATE,
        PERM_DATASET_VERSIONS,
        PERM_SEMANTIC_READ,
        PERM_SEMANTIC_CREATE,
        PERM_SEMANTIC_UPDATE,
        PERM_SEMANTIC_DELETE,
        PERM_SEMANTIC_VERIFY,
        PERM_SEMANTIC_PUBLISH,
        PERM_GRAPH_READ,
        PERM_GRAPH_CREATE,
        PERM_GRAPH_UPDATE,
        PERM_GRAPH_DELETE,
        PERM_GRAPH_TRAVERSE,
        PERM_GRAPH_PUBLISH,
        PERM_LLM_READ,
        PERM_LLM_MANAGE,
        PERM_LLM_POLICY_READ,
        PERM_LLM_POLICY_UPDATE,
        PERM_LLM_MODEL_APPROVE,
        PERM_LLM_MODEL_DISABLE,
        PERM_LLM_USAGE_READ,
        PERM_ORCHESTRATION_EXECUTE,
        PERM_ORCHESTRATION_READ,
        PERM_ORCHESTRATION_MANAGE,
        PERM_GOVERNANCE_READ,
        PERM_GOVERNANCE_CREATE,
        PERM_GOVERNANCE_REVIEW,
        PERM_GOVERNANCE_APPROVE,
        PERM_GOVERNANCE_REJECT,
        PERM_GOVERNANCE_MANAGE_POLICY,
        PERM_GOVERNANCE_VIEW_AUDIT,
        PERM_EVALUATION_MONITOR_READ,
        PERM_EVALUATION_BENCHMARK_MANAGE,
        PERM_EVALUATION_RUN_EXECUTE,
        PERM_EVALUATION_QUALITY_GATE_READ,
        PERM_EVALUATION_RELEASE_APPROVE,
        PERM_EVALUATION_HUMAN_REVIEW,
        PERM_SRE_ALERT_READ,
        PERM_SRE_ALERT_MANAGE,
        PERM_SRE_INCIDENT_READ,
        PERM_SRE_INCIDENT_MANAGE,
        PERM_SRE_RUNBOOK_READ,
        PERM_SRE_RUNBOOK_MANAGE,
        PERM_SRE_SLO_READ,
        PERM_SRE_SLO_MANAGE,
        PERM_SRE_MAINTENANCE_MANAGE,
        PERM_SRE_RELEASE_GATE_READ,
        PERM_RELIABILITY_READ,
        PERM_RELIABILITY_RUN,
        PERM_RELIABILITY_MANAGE,
        PERM_RELIABILITY_READINESS,
        PERM_COMPLIANCE_READ,
        PERM_COMPLIANCE_ASSESS,
        PERM_COMPLIANCE_MANAGE,
        PERM_COMPLIANCE_EVIDENCE_READ,
        PERM_COMPLIANCE_EVIDENCE_MANAGE,
        PERM_COMPLIANCE_FINDINGS_READ,
        PERM_COMPLIANCE_FINDINGS_MANAGE,
        PERM_COMPLIANCE_ACCESS_REVIEW,
        PERM_COMPLIANCE_RETENTION_MANAGE,
        PERM_COMPLIANCE_PRIVACY_MANAGE,
        PERM_COMPLIANCE_RISK_ACCEPTANCE,
        PERM_COMPLIANCE_SECURITY_ADMIN,
        PERM_FINOPS_READ,
        PERM_FINOPS_MANAGE,
        PERM_FINOPS_BUDGET_READ,
        PERM_FINOPS_BUDGET_MANAGE,
        PERM_FINOPS_QUOTA_MANAGE,
        PERM_FINOPS_PRICING_MANAGE,
        PERM_FINOPS_ANOMALY_READ,
        PERM_FINOPS_POLICY_MANAGE,
        PERM_FINOPS_RECONCILIATION_READ,
        PERM_FINOPS_OPTIMIZATION_READ,
    }
    assert set(SYSTEM_PERMISSIONS.keys()) == expected_permissions
    assert len(SYSTEM_PERMISSIONS) == 138

    for perm_name, desc in SYSTEM_PERMISSIONS.items():
        assert isinstance(perm_name, str) and "." in perm_name
        assert isinstance(desc, str) and len(desc) > 5


def test_system_roles_definitions() -> None:
    """Verify system role definitions exist for Admin, Analyst, and Viewer."""
    assert ROLE_ADMIN in SYSTEM_ROLES
    assert ROLE_ANALYST in SYSTEM_ROLES
    assert ROLE_VIEWER in SYSTEM_ROLES
    assert len(SYSTEM_ROLES) == 3


def test_admin_role_has_all_permissions() -> None:
    """Verify Admin role has all system permissions without exception."""
    admin_perms = DEFAULT_ROLE_PERMISSIONS[ROLE_ADMIN]
    assert admin_perms == set(SYSTEM_PERMISSIONS.keys())
    assert len(admin_perms) == 138


def test_analyst_role_permissions_matrix() -> None:
    """Verify Analyst role permissions match Task 5 specification."""
    analyst_perms = DEFAULT_ROLE_PERMISSIONS[ROLE_ANALYST]

    # Required permissions for Analyst
    assert PERM_ORGANIZATION_READ in analyst_perms
    assert PERM_DOCUMENTS_READ in analyst_perms
    assert PERM_DOCUMENTS_WRITE in analyst_perms
    assert PERM_DATASETS_READ in analyst_perms
    assert PERM_DATASETS_WRITE in analyst_perms
    assert PERM_DATA_SOURCES_READ in analyst_perms
    assert PERM_REPORTS_READ in analyst_perms
    assert PERM_REPORTS_CREATE in analyst_perms
    assert PERM_ANALYTICS_READ in analyst_perms
    assert PERM_ANALYTICS_EXECUTE in analyst_perms
    assert PERM_AI_CHAT in analyst_perms
    assert PERM_AI_ANALYZE in analyst_perms
    assert PERM_GOVERNANCE_READ in analyst_perms
    assert PERM_GOVERNANCE_CREATE in analyst_perms
    assert PERM_GOVERNANCE_REVIEW in analyst_perms
    assert PERM_GOVERNANCE_VIEW_AUDIT in analyst_perms
    assert PERM_EVALUATION_MONITOR_READ in analyst_perms
    assert PERM_EVALUATION_BENCHMARK_MANAGE in analyst_perms
    assert PERM_EVALUATION_RUN_EXECUTE in analyst_perms
    assert PERM_EVALUATION_QUALITY_GATE_READ in analyst_perms
    assert PERM_EVALUATION_HUMAN_REVIEW in analyst_perms

    # Denied permissions for Analyst
    assert PERM_EVALUATION_RELEASE_APPROVE not in analyst_perms
    assert PERM_GOVERNANCE_MANAGE_POLICY not in analyst_perms
    assert PERM_USERS_MANAGE not in analyst_perms
    assert PERM_USERS_REMOVE not in analyst_perms
    assert PERM_DOCUMENTS_DELETE not in analyst_perms
    assert PERM_DOCUMENTS_MANAGE not in analyst_perms
    assert PERM_ORGANIZATION_MANAGE not in analyst_perms
    assert PERM_AUDIT_READ not in analyst_perms
    assert PERM_USAGE_READ not in analyst_perms


def test_viewer_role_permissions_matrix() -> None:
    """Verify Viewer role permissions match Task 5 specification."""
    viewer_perms = DEFAULT_ROLE_PERMISSIONS[ROLE_VIEWER]

    # Required read permissions for Viewer
    assert PERM_ORGANIZATION_READ in viewer_perms
    assert PERM_DOCUMENTS_READ in viewer_perms
    assert PERM_DATASETS_READ in viewer_perms
    assert PERM_REPORTS_READ in viewer_perms
    assert PERM_ANALYTICS_READ in viewer_perms
    assert PERM_AI_CHAT in viewer_perms
    assert PERM_GOVERNANCE_READ in viewer_perms
    assert PERM_GOVERNANCE_VIEW_AUDIT in viewer_perms
    assert PERM_EVALUATION_MONITOR_READ in viewer_perms
    assert PERM_EVALUATION_QUALITY_GATE_READ in viewer_perms

    # Denied write/management/executive permissions for Viewer
    assert PERM_EVALUATION_BENCHMARK_MANAGE not in viewer_perms
    assert PERM_EVALUATION_RUN_EXECUTE not in viewer_perms
    assert PERM_EVALUATION_RELEASE_APPROVE not in viewer_perms
    assert PERM_EVALUATION_HUMAN_REVIEW not in viewer_perms
    assert PERM_GOVERNANCE_CREATE not in viewer_perms
    assert PERM_GOVERNANCE_APPROVE not in viewer_perms
    assert PERM_GOVERNANCE_REJECT not in viewer_perms
    assert PERM_GOVERNANCE_MANAGE_POLICY not in viewer_perms
    assert PERM_USERS_MANAGE not in viewer_perms
    assert PERM_DOCUMENTS_WRITE not in viewer_perms
    assert PERM_DOCUMENTS_DELETE not in viewer_perms
    assert PERM_DATASETS_WRITE not in viewer_perms
    assert PERM_REPORTS_CREATE not in viewer_perms
    assert PERM_ANALYTICS_EXECUTE not in viewer_perms
    assert PERM_AI_ANALYZE not in viewer_perms
    assert PERM_AUDIT_READ not in viewer_perms
