"""Domain models for Secure SQL Agent & Structured Data Analysis."""

from dataclasses import dataclass, field
from typing import Any
from uuid import UUID


@dataclass(frozen=True)
class ColumnSchema:
    """Schema definition for an individual table or dataset column."""

    name: str
    data_type: str
    nullable: bool = True
    is_primary_key: bool = False
    description: str | None = None


@dataclass(frozen=True)
class TableSchema:
    """Schema definition for an individual tabular entity."""

    name: str
    description: str | None = None
    row_estimate: int | None = None
    columns: list[ColumnSchema] = field(default_factory=list)

    @property
    def column_names(self) -> set[str]:
        return {c.name.lower() for c in self.columns}


@dataclass(frozen=True)
class RelationshipSchema:
    """Foreign-key or schema-level relational link between tables."""

    from_table: str
    from_column: str
    to_table: str
    to_column: str


@dataclass(frozen=True)
class SchemaContext:
    """Tenant-scoped tabular schema catalog exposed to the SQL Agent."""

    datasource_id: UUID
    organization_id: UUID
    dialect: str
    tables: dict[str, TableSchema] = field(default_factory=dict)
    relationships: list[RelationshipSchema] = field(default_factory=list)

    @property
    def allowed_tables(self) -> set[str]:
        """Return lowercased table names allowed for querying."""
        return {tbl.lower() for tbl in self.tables}

    @property
    def allowed_columns(self) -> dict[str, set[str]]:
        """Return map of lowercased table -> lowercased column names."""
        return {tbl_name.lower(): tbl.column_names for tbl_name, tbl in self.tables.items()}

    def format_ddl_representation(self) -> str:
        """Format clean, injection-safe pseudo-DDL representation for prompt context."""
        ddl_parts: list[str] = []
        for tbl_name, tbl in sorted(self.tables.items()):
            col_strs: list[str] = []
            for col in tbl.columns:
                pk_marker = " PRIMARY KEY" if col.is_primary_key else ""
                null_marker = "" if col.nullable else " NOT NULL"
                desc = f" -- {col.description}" if col.description else ""
                col_strs.append(f"  {col.name} {col.data_type}{pk_marker}{null_marker}{desc}")
            cols_block = ",\n".join(col_strs)
            ddl_parts.append(f"CREATE TABLE {tbl_name} (\n{cols_block}\n);")

        if self.relationships:
            ddl_parts.append("\n-- Relationships:")
            for rel in self.relationships:
                ddl_parts.append(
                    f"-- {rel.from_table}.{rel.from_column} -> {rel.to_table}.{rel.to_column}"
                )

        return "\n\n".join(ddl_parts)


@dataclass(frozen=True)
class GeneratedSQL:
    """SQL statement generated by a provider."""

    sql: str
    dialect: str
    tables_used: list[str] = field(default_factory=list)
    columns_used: list[str] = field(default_factory=list)
    confidence: float = 0.95
    explanation: str | None = None


@dataclass(frozen=True)
class SQLComplexityMetrics:
    """AST-derived complexity counts for an analyzed statement."""

    table_count: int
    join_count: int
    cte_count: int
    subquery_count: int


@dataclass(frozen=True)
class SQLQueryResult:
    """Data rows and columns produced by read-only query execution."""

    columns: list[str]
    rows: list[dict[str, Any]]
    row_count: int
    truncated: bool = False
    duration_ms: float = 0.0


@dataclass(frozen=True)
class SQLProvenance:
    """Immutable audit and verification provenance metadata for executed SQL."""

    sql_hash: str
    datasource_id: str
    tables_used: list[str]
    columns_used: list[str]
    row_count: int
    duration_ms: float
    normalized_sql: str


@dataclass(frozen=True)
class StructuredAnalysisResult:
    """Controlled analytical outputs computed in Python/Pandas without LLM arithmetic."""

    summary: str
    metrics: dict[str, Any] = field(default_factory=dict)
    comparisons: list[dict[str, Any]] = field(default_factory=list)
    trends: list[dict[str, Any]] = field(default_factory=list)


@dataclass(frozen=True)
class SQLAgentResult:
    """Complete end-to-end outcome returned by SQLAgentService."""

    question: str
    generated_sql: str
    sql_hash: str
    query_result: SQLQueryResult
    analysis: StructuredAnalysisResult | None
    provenance: SQLProvenance
    diagnostics: dict[str, Any] = field(default_factory=dict)
