"""add_observability_columns_to_llm_requests

Revision ID: 14cf751d60fd
Revises: 70d117451cd6
Create Date: 2026-09-06 11:48:33.060268

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14cf751d60fd"
down_revision: str | Sequence[str] | None = "70d117451cd6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm_requests", sa.Column("trace_id", sa.String(length=64), nullable=True))
    op.add_column("llm_requests", sa.Column("span_id", sa.String(length=32), nullable=True))
    op.add_column("llm_requests", sa.Column("request_id", sa.String(length=64), nullable=True))
    op.create_index(
        op.f("ix_llm_requests_request_id"), "llm_requests", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_llm_requests_trace_id"), "llm_requests", ["trace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_requests_trace_id"), table_name="llm_requests")
    op.drop_index(op.f("ix_llm_requests_request_id"), table_name="llm_requests")
    op.drop_column("llm_requests", "request_id")
    op.drop_column("llm_requests", "span_id")
    op.drop_column("llm_requests", "trace_id")
    # ### end Alembic commands ###
