"""add_chunk_embedding_indexing_status

Revision ID: 18223763f7b0
Revises: 29982017b2bb
Create Date: 2026-09-05 14:00:09.884511

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18223763f7b0"
down_revision: str | Sequence[str] | None = "29982017b2bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunk_embeddings",
        sa.Column(
            "indexing_status", sa.String(length=50), server_default="pending", nullable=False
        ),
    )
    op.add_column("document_chunk_embeddings", sa.Column("point_id", sa.UUID(), nullable=True))
    op.add_column(
        "document_chunk_embeddings",
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_chunk_embeddings_org_indexing",
        "document_chunk_embeddings",
        ["organization_id", "indexing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunk_embeddings_indexing_status"),
        "document_chunk_embeddings",
        ["indexing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunk_embeddings_point_id"),
        "document_chunk_embeddings",
        ["point_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_chunk_embeddings_point_id"), table_name="document_chunk_embeddings"
    )
    op.drop_index(
        op.f("ix_document_chunk_embeddings_indexing_status"), table_name="document_chunk_embeddings"
    )
    op.drop_index("ix_chunk_embeddings_org_indexing", table_name="document_chunk_embeddings")
    op.drop_column("document_chunk_embeddings", "indexed_at")
    op.drop_column("document_chunk_embeddings", "point_id")
    op.drop_column("document_chunk_embeddings", "indexing_status")
    # ### end Alembic commands ###
