"""add_document_chunk_embeddings

Revision ID: 29982017b2bb
Revises: b2c272705698
Create Date: 2026-09-05 13:45:56.055065

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29982017b2bb"
down_revision: str | Sequence[str] | None = "b2c272705698"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_chunk_embeddings",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("normalization", sa.String(length=50), nullable=False),
        sa.Column("embedding_input_hash", sa.String(length=64), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chunk_id"], ["document_chunks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chunk_embeddings_hash",
        "document_chunk_embeddings",
        ["organization_id", "embedding_input_hash"],
        unique=False,
    )
    op.create_index(
        "ix_chunk_embeddings_org_chunk",
        "document_chunk_embeddings",
        ["organization_id", "chunk_id"],
        unique=False,
    )
    op.create_index(
        "ix_chunk_embeddings_org_doc",
        "document_chunk_embeddings",
        ["organization_id", "document_id"],
        unique=False,
    )
    op.create_index(
        "ix_chunk_embeddings_status",
        "document_chunk_embeddings",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunk_embeddings_chunk_id"),
        "document_chunk_embeddings",
        ["chunk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunk_embeddings_document_id"),
        "document_chunk_embeddings",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunk_embeddings_embedding_input_hash"),
        "document_chunk_embeddings",
        ["embedding_input_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunk_embeddings_organization_id"),
        "document_chunk_embeddings",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunk_embeddings_status"),
        "document_chunk_embeddings",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_chunk_embeddings_status"), table_name="document_chunk_embeddings"
    )
    op.drop_index(
        op.f("ix_document_chunk_embeddings_organization_id"), table_name="document_chunk_embeddings"
    )
    op.drop_index(
        op.f("ix_document_chunk_embeddings_embedding_input_hash"),
        table_name="document_chunk_embeddings",
    )
    op.drop_index(
        op.f("ix_document_chunk_embeddings_document_id"), table_name="document_chunk_embeddings"
    )
    op.drop_index(
        op.f("ix_document_chunk_embeddings_chunk_id"), table_name="document_chunk_embeddings"
    )
    op.drop_index("ix_chunk_embeddings_status", table_name="document_chunk_embeddings")
    op.drop_index("ix_chunk_embeddings_org_doc", table_name="document_chunk_embeddings")
    op.drop_index("ix_chunk_embeddings_org_chunk", table_name="document_chunk_embeddings")
    op.drop_index("ix_chunk_embeddings_hash", table_name="document_chunk_embeddings")
    op.drop_table("document_chunk_embeddings")
    # ### end Alembic commands ###
