"""add_report_versions_and_fields

Revision ID: 64b3759f3c21
Revises: 18223763f7b0
Create Date: 2026-09-06 11:05:51.554506

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64b3759f3c21"
down_revision: str | Sequence[str] | None = "18223763f7b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_versions",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("document_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "report_id", "version_number", name="uq_report_versions_report_version"
        ),
    )
    op.create_index(
        op.f("ix_report_versions_organization_id"),
        "report_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_versions_report_id"), "report_versions", ["report_id"], unique=False
    )
    op.add_column(
        "reports", sa.Column("current_version", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column("reports", sa.Column("published_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("reports", sa.Column("content_hash", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "content_hash")
    op.drop_column("reports", "published_at")
    op.drop_column("reports", "current_version")
    op.drop_index(op.f("ix_report_versions_report_id"), table_name="report_versions")
    op.drop_index(op.f("ix_report_versions_organization_id"), table_name="report_versions")
    op.drop_table("report_versions")
    # ### end Alembic commands ###
