"""add_document_storage_fields

Revision ID: 89abc7124cf4
Revises: 7bd2713f8061
Create Date: 2026-09-05 12:53:53.756275

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89abc7124cf4"
down_revision: str | Sequence[str] | None = "7bd2713f8061"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("detected_mime_type", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "documents",
        sa.Column("sha256", sa.String(length=64), server_default="", nullable=False),
    )
    op.add_column(
        "documents",
        sa.Column("storage_backend", sa.String(length=50), server_default="local", nullable=False),
    )
    op.add_column("documents", sa.Column("failure_reason", sa.Text(), nullable=True))
    op.add_column(
        "documents",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_documents_org_deleted_at",
        "documents",
        ["organization_id", "deleted_at"],
        unique=False,
    )
    op.create_index(
        "uq_documents_org_sha256_active",
        "documents",
        ["organization_id", "sha256"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND status != 'deleted' AND sha256 != ''"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_documents_org_sha256_active", table_name="documents", if_exists=True)
    op.drop_index("ix_documents_org_sha256", table_name="documents", if_exists=True)
    op.drop_index("ix_documents_org_deleted_at", table_name="documents", if_exists=True)
    op.drop_column("documents", "deleted_at")
    op.drop_column("documents", "failure_reason")
    op.drop_column("documents", "storage_backend")
    op.drop_column("documents", "sha256")
    op.drop_column("documents", "detected_mime_type")
    # ### end Alembic commands ###
