"""add_document_ingestion_fields

Revision ID: fb0a9ae0683a
Revises: 89abc7124cf4
Create Date: 2026-09-05 13:12:49.801304

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb0a9ae0683a"
down_revision: str | Sequence[str] | None = "89abc7124cf4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "documents",
        sa.Column("parsed_storage_key", sa.String(length=500), nullable=True),
    )
    op.add_column("documents", sa.Column("parser_name", sa.String(length=50), nullable=True))
    op.add_column("documents", sa.Column("parser_version", sa.String(length=50), nullable=True))
    op.add_column("documents", sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "documents",
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "metadata")
    op.drop_column("documents", "parsed_at")
    op.drop_column("documents", "parser_version")
    op.drop_column("documents", "parser_name")
    op.drop_column("documents", "parsed_storage_key")
    # ### end Alembic commands ###
