"""add_agent_runtime_tables

Revision ID: fb758e565435
Revises: 5fb83db2f1c4
Create Date: 2026-09-06 12:53:11.944251

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb758e565435"
down_revision: str | Sequence[str] | None = "5fb83db2f1c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_sessions",
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("agent_type", sa.String(length=100), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=True),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("max_steps", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("final_answer", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agent_sessions_created_at", "agent_sessions", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_agent_sessions_created_by"), "agent_sessions", ["created_by"], unique=False
    )
    op.create_index(
        "ix_agent_sessions_org_status",
        "agent_sessions",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_sessions_organization_id"),
        "agent_sessions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_agent_sessions_status"), "agent_sessions", ["status"], unique=False)

    op.create_table(
        "agent_plans",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("estimated_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_duration", sa.Float(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["agent_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_plans_organization_id"), "agent_plans", ["organization_id"], unique=False
    )
    op.create_index("ix_agent_plans_session_id", "agent_plans", ["session_id"], unique=False)

    op.create_foreign_key(
        "fk_agent_sessions_plan_id_agent_plans",
        "agent_sessions",
        "agent_plans",
        ["plan_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "agent_steps",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("tool_input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plan_id"], ["agent_plans.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["agent_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_steps_organization_id"), "agent_steps", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_agent_steps_session_seq", "agent_steps", ["session_id", "sequence"], unique=False
    )
    op.create_table(
        "agent_checkpoints",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("tool_input_hash", sa.String(length=64), nullable=False),
        sa.Column("tool_result_reference", sa.String(length=255), nullable=True),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["agent_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["step_id"], ["agent_steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_checkpoints_organization_id"),
        "agent_checkpoints",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_agent_checkpoints_session_step",
        "agent_checkpoints",
        ["session_id", "step_id"],
        unique=False,
    )
    op.create_table(
        "approval_requests",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["agent_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["step_id"], ["agent_steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approval_requests_organization_id"),
        "approval_requests",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_approval_requests_session_status",
        "approval_requests",
        ["session_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_agent_sessions_plan_id_agent_plans", "agent_sessions", type_="foreignkey"
    )
    op.drop_index("ix_approval_requests_session_status", table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_organization_id"), table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index("ix_agent_checkpoints_session_step", table_name="agent_checkpoints")
    op.drop_index(op.f("ix_agent_checkpoints_organization_id"), table_name="agent_checkpoints")
    op.drop_table("agent_checkpoints")
    op.drop_index("ix_agent_steps_session_seq", table_name="agent_steps")
    op.drop_index(op.f("ix_agent_steps_organization_id"), table_name="agent_steps")
    op.drop_table("agent_steps")
    op.drop_index("ix_agent_plans_session_id", table_name="agent_plans")
    op.drop_index(op.f("ix_agent_plans_organization_id"), table_name="agent_plans")
    op.drop_table("agent_plans")
    op.drop_index(op.f("ix_agent_sessions_status"), table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_organization_id"), table_name="agent_sessions")
    op.drop_index("ix_agent_sessions_org_status", table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_created_by"), table_name="agent_sessions")
    op.drop_index("ix_agent_sessions_created_at", table_name="agent_sessions")
    op.drop_table("agent_sessions")
    # ### end Alembic commands ###
