"""Domain models for evidence selection, context assembly, and grounded RAG answers."""

from dataclasses import dataclass, field
from enum import StrEnum
from uuid import UUID

from app.query.models import SearchPlan


@dataclass
class Evidence:
    """Individual unit of retrieved document context selected for RAG generation."""

    evidence_id: str
    chunk_id: UUID
    document_id: UUID
    organization_id: UUID
    rank: int
    rerank_score: float | None
    text: str
    page_number: int | None = None
    heading_path: str | None = None
    heading_context: str | None = None
    section: str | None = None
    source_locator: str | None = None
    document_name: str | None = None
    parent_text: str | None = None


@dataclass
class CitationReference:
    """Strongly typed mapping linking an evidence marker to concrete source metadata."""

    evidence_id: str
    chunk_id: UUID
    document_id: UUID
    page_number: int | None = None
    source_locator: str | None = None
    document_name: str | None = None


@dataclass
class GroundedAnswer:
    """Validated, evidence-grounded answer generated by LLM provider."""

    answer: str
    evidence_ids: list[str]
    grounded: bool
    confidence: float
    system_grounding_confidence: float
    model_confidence: float | None = None
    is_contradictory: bool = False
    citations: list[CitationReference] = field(default_factory=list)
    language: str = "en"
    model: str = ""
    prompt_version: str = "v1"


@dataclass
class RAGDiagnostics:
    """Fine-grained execution latency, token accounting, and observability metrics."""

    understanding_ms: float = 0.0
    retrieval_ms: float = 0.0
    rerank_ms: float = 0.0
    evidence_selection_ms: float = 0.0
    context_assembly_ms: float = 0.0
    llm_latency_ms: float = 0.0
    total_ms: float = 0.0
    retrieved_count: int = 0
    reranked_count: int = 0
    evidence_count: int = 0
    context_tokens: int = 0
    input_tokens: int = 0
    output_tokens: int = 0
    model: str = ""
    provider: str = ""
    prompt_version: str = "v1"
    cost_usd: float = 0.0
    fallback_used: bool = False


@dataclass
class RAGAnswerResult:
    """Complete aggregated result returned by RAGService orchestration."""

    query: str
    answer: GroundedAnswer
    evidence: list[Evidence]
    search_plan: SearchPlan | None = None
    diagnostics: RAGDiagnostics = field(default_factory=RAGDiagnostics)


class RAGEventType(StrEnum):
    """Lifecycle event types for streaming and observable RAG execution."""

    QUERY_ANALYZED = "query_analyzed"
    RETRIEVAL_STARTED = "retrieval_started"
    RETRIEVAL_COMPLETED = "retrieval_completed"
    RERANKING_STARTED = "reranking_started"
    RERANKING_COMPLETED = "reranking_completed"
    CONTEXT_BUILT = "context_built"
    GENERATION_STARTED = "generation_started"
    GENERATION_COMPLETED = "generation_completed"
    ERROR = "error"


@dataclass
class RAGEvent:
    """Typed event payload for future SSE event streams."""

    event_type: RAGEventType
    payload: dict[str, object] = field(default_factory=dict)
