"""Pydantic request and response schemas for RAG API endpoints."""

from uuid import UUID

from pydantic import BaseModel, Field


class RAGAnswerRequest(BaseModel):
    """Request payload for evidence-grounded answer generation."""

    query: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="User question to answer grounded strictly in enterprise documents",
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Maximum number of evidence chunks to assemble into context",
    )
    include_evidence: bool = Field(
        default=True,
        description="Whether to return full text of assembled evidence blocks in response",
    )
    conversation_id: UUID | None = Field(
        default=None,
        description="Optional conversation thread identifier to associate execution with",
    )
    analysis_run_id: UUID | None = Field(
        default=None,
        description="Optional multi-step analysis run identifier for trace persistence",
    )


class CitationResponse(BaseModel):
    """Citation mapping an evidence ID to concrete document and chunk identifiers."""

    evidence_id: str = Field(..., description="Evidence identifier (e.g. E1, E2)")
    chunk_id: UUID = Field(..., description="Unique chunk identifier")
    document_id: UUID = Field(..., description="Document identifier")
    page_number: int | None = Field(default=None, description="Page number of the citation")
    source_locator: str | None = Field(
        default=None, description="Human-readable citation source locator"
    )
    document_name: str | None = Field(default=None, description="Name or title of source document")


class EvidenceResponse(BaseModel):
    """Assembled evidence context block returned in API response."""

    evidence_id: str = Field(..., description="Assigned evidence identifier")
    document_name: str | None = Field(default=None, description="Source document name")
    page_number: int | None = Field(default=None, description="Source page number")
    section: str | None = Field(default=None, description="Section heading")
    text: str = Field(..., description="Extracted chunk text or parent context")
    rerank_score: float | None = Field(default=None, description="Cross-encoder relevance score")


class RAGDiagnosticsResponse(BaseModel):
    """Execution telemetry and latency breakdown for RAG answer generation."""

    retrieved: int = Field(default=0, description="Total candidates retrieved")
    reranked: int = Field(default=0, description="Candidates scored by cross-encoder")
    evidence_used: int = Field(default=0, description="Number of evidence chunks assembled")
    context_tokens: int = Field(default=0, description="Estimated tokens in assembled context")
    input_tokens: int = Field(default=0, description="Input tokens consumed by LLM")
    output_tokens: int = Field(default=0, description="Output tokens generated by LLM")
    understanding_ms: float = Field(default=0.0, description="Query understanding latency in ms")
    retrieval_ms: float = Field(default=0.0, description="Hybrid retrieval latency in ms")
    rerank_ms: float = Field(default=0.0, description="Cross-encoder reranking latency in ms")
    llm_latency_ms: float = Field(default=0.0, description="LLM generation latency in ms")
    total_latency_ms: float = Field(default=0.0, description="Total pipeline latency in ms")
    model: str = Field(default="", description="LLM generation model used")
    provider: str = Field(default="", description="LLM provider name")
    prompt_version: str = Field(default="v1", description="System prompt template version")


class RAGAnswerResponse(BaseModel):
    """Evidence-grounded response containing answer, citations, and evidence."""

    answer: str = Field(..., description="Factual answer grounded in supplied documents")
    grounded: bool = Field(..., description="True if answer is verified by provided evidence")
    confidence: float = Field(..., description="Confidence score bounded between 0.0 and 1.0")
    citations: list[CitationResponse] = Field(
        default_factory=list, description="Citations referenced in the generated answer"
    )
    evidence: list[EvidenceResponse] = Field(
        default_factory=list, description="Supplied evidence blocks (if requested)"
    )
    diagnostics: RAGDiagnosticsResponse = Field(
        ..., description="Execution telemetry and diagnostic breakdown"
    )
